RELEASE_ID=${1}
ENVIRONMENT=${2}
TEMP_DIR=${3}

echo "START - REMOTE CLEANUP in ENVIRONMENT : " $ENVIRONMENT
echo "RELEASE_ID : " $RELEASE_ID
echo "TEMP_DIR : " $TEMP_DIR

rm -rf $TEMP_DIR/$RELEASE_ID/

rm -rf $TEMP_DIR/scripts/

rm -rf $TEMP_DIR/${RELEASE_ID}*

echo "END - REMOTE CLEANUP in ENVIRONMENT : " $ENVIRONMENT